### ISSUE TITLE
Channelz implementation progress tracking

### ISSUE THREAD

**Issue by lyuxuan** [lyuxuan/grpc-go#2]
- [x] channelz database internals, APIs, interfaces. Entity registration/deletion instrumentation. (https://github.com/grpc/grpc-go/pull/1811)
- [x] Entity metric collection instrumentation. (https://github.com/grpc/grpc-go/pull/1909)
- [ ] rpc service implementation
- [ ] insignificant info to be filled in: refName, security, socket options, etc.
